from fastapi.testclient import TestClient

from hr_agent.orchestration import build_orchestration_graph, run_workflow
from hr_agent.web.app import app


def test_health_endpoint():
    client = TestClient(app)
    response = client.get("/health")
    assert response.status_code == 200
    payload = response.json()
    assert payload["status"] == "ok"
    assert "mcp" in payload
    assert "vector_store" in payload


def test_chat_endpoint_returns_answer():
    client = TestClient(app)
    response = client.post("/chat", json={"message": "How much PTO do employees accrue per month?"})
    assert response.status_code == 200
    payload = response.json()
    assert "answer" in payload
    assert payload["answer"]


def test_chat_endpoint_uses_orchestration_for_employee_requests():
    client = TestClient(app)
    response = client.post("/chat", json={"message": "What is my PTO balance for employee E-1001?"})
    assert response.status_code == 200
    payload = response.json()
    assert "E-1001" in payload["answer"]
    assert payload["answer"].lower().count("balance") >= 1
    assert payload["citations"]


def test_chat_endpoint_uses_compliance_tool_message_for_expense_questions():
    client = TestClient(app)
    response = client.post("/chat", json={"message": "Can I expense a company laptop and home office chair?"})
    assert response.status_code == 200
    payload = response.json()
    lowered = payload["answer"].lower()
    assert "expense reimbursement" in lowered or "policy review" in lowered
    assert "PTO" not in payload["answer"]
    assert payload["citations"]


def test_employee_profile_prompts_route_to_employee_data_workflow():
    result = run_workflow("Show me the employee profile for E-1001.")
    assert result["intent"] == "employee_data_request"
    assert result["needs_tool"] is True
    assert result["tool_name"] == "lookup_employee_profile"
    assert "E-1001" in result["answer"]


def test_cors_headers_for_local_frontend():
    client = TestClient(app)
    response = client.options(
        "/chat",
        headers={
            "Origin": "http://localhost:5174",
            "Access-Control-Request-Method": "POST",
        },
    )
    assert response.status_code == 200
    assert response.headers["access-control-allow-origin"] == "http://localhost:5174"


def test_langgraph_workflow_returns_structured_answer():
    graph = build_orchestration_graph()
    result = graph.invoke({"query": "How much PTO do employees accrue per month?"})
    assert result["intent"] == "policy_question"
    assert result["needs_tool"] is False
    assert "answer" in result
    assert result["answer"]
    assert result["citations"]

    result_dict = run_workflow("How much PTO do employees accrue per month?")
    assert result_dict["intent"] == "policy_question"
    assert result_dict["needs_tool"] is False


def test_langgraph_routes_employee_data_requests_to_tool_workflow():
    result = run_workflow("What is my PTO balance for employee E-1001?")
    assert result["intent"] == "employee_data_request"
    assert result["needs_tool"] is True
    assert result["tool_name"] == "check_pto_balance"
    assert "E-1001" in result["answer"] or "balance" in result["answer"].lower()
    assert result.get("tool_result")
    assert result["citations"]

    payload = result["tool_result"]
    if isinstance(payload, dict):
        assert payload["employee_id"] == "E-1001"
    else:
        assert "E-1001" in str(payload)


def test_llm_answer_override_is_used_when_configured(monkeypatch):
    import hr_agent.answering as answering

    def fake_generate_answer(prompt: str, *, model: str | None = None) -> str:
        assert "PTO" in prompt
        assert model is None or model
        return "This answer was generated by Gemini."

    monkeypatch.setattr(answering, "generate_answer", fake_generate_answer)
    monkeypatch.setattr(answering.settings, "gemini_api_key", "demo-key")

    result = answering.generate_final_answer(
        "How much PTO do employees accrue per month?",
        tool_result=None,
        corpus_dir="corpus",
        k=3,
    )

    assert result["answer"] == "This answer was generated by Gemini."
    assert result["citations"]
